env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "XIN1l/sSIdBPaJAgZ/+pm3yTSeTFH1Rc5Ncus2bQBlqxiAPp2U7u163EyRQxWfLOEFjtVlDfEQOsi4IWSo4l2ZedNgBocNb9wFoMupwe+h+jMi2q3WEQ204JSSWWkuxyqNT0JYm2zc1VsoyCXQSy8z8pWdAv3Vry49dfalXebag="

language: c++

compiler:
  - gcc

script:
  - cd $TRAVIS_BUILD_DIR/build
  - make install
  - cd $TRAVIS_BUILD_DIR/build/install
  - find
  - cp -r lib/* bin
  - cd bin
  - LD_LIBRARY_PATH=. ./Capu_Test

before_install:
  - cd ..
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.10.tar.gz
  - tar xf cmake-2.8.10.tar.gz
  - cd cmake-2.8.10

install:
  - sudo apt-get install libcurl3-dev
  - ./bootstrap --system-curl
  - make -j4
  - sudo make install
  
addons:
  coverity_scan:
    project:
      name: "veithm/capu"
      description: "Collections and Platform Utils"
    notification_email: martin.veith@bmw-carit.de
    build_command_prepend: "cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/Linux_X86_64.toolchain -DCMAKE_BUILD_TYPE:String=Release -DCapu_BUILD_TESTS:BOOL=1 -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/build/install ../"
    build_command: "make -j4"
    branch_pattern: master
